apiVersion: v1
kind: Service
metadata:
  name: vote
  labels:
    app: vote
spec:
  type: NodePort
  ports:
    - port: 8080
      name: "vote-services"
      targetPort: 80
      nodePort: 31000
  selector:
    app: vote
     